package Lab9;

// Inheritance Mapping 
// 3) Table Per Concrete class Mapping using XML Configuration
// Inserting Records in Students1 table and related tables(CurrentStudent1,WeekdayStudent1,WeekendStudent1,OldStudent1) which are inherited from student table using XML configuration
import org.hibernate.*;

public class Lab9A {

	public static void main(String[] args) {
		Transaction tx = null;

		try {
			SessionFactory sf = HibernateUtil.getSessionFactory();
			Session session = sf.openSession();
			tx = session.beginTransaction();

			// 1. Adding the Student
			Student stu = new Student("Dev", "Kolkata", "Enabled", 15000.00);
			Integer it = (Integer) session.save(stu); // returns P.K Value which is generated for this INSERT Query
			System.out.println(it.intValue()); // 1 // All operation returns 1 only becoz each inserting in different
												// Table for each P.C Separately So, P.K also will be generate from 1
												// for each table
												// In XML config Hibernate will Submit a Select Query to get Max Value
												// of P.K (ID column)
												// then it will first do increments and provide the P.K value to Query
												// generated by Hibernate
			// 2. Adding the CurrentStudent
			CurrentStudent cstu = new CurrentStudent("Mahadev", "Bangalore", "Enabled", 2000.00, 1000.00, "6:30 p.m",
					"BTM");
			it = (Integer) session.save(cstu);
			System.out.println(it.intValue()); // 1

			// 3. Adding the OldStudent
			OldStudent ostu = new OldStudent("DDD", "Blore", "Enabled", 14000.00, "TCS", "ddd@tcs.com", 9.0);
			it = (Integer) session.save(ostu);
			System.out.println(it.intValue()); // 1

			// 4. Adding the WeekdayStudent
			WeekdayStudent wdstu = new WeekdayStudent("PPP", "Kolkata", "Enabled", 16000.00, 12000.00, "6:30 p.m",
					"BTM", "B-tech", "82", 2016);
			it = (Integer) session.save(wdstu);
			System.out.println(it.intValue()); // 1

			// 5. Adding the WeekendStudent
			WeekendStudent wstu = new WeekendStudent("SSS", "Delhi", "Enabled", 17000.00, 14000.00, "6:30 p.m", "BTM",
					"Google", "sss@google.com", 40.0);
			it = (Integer) session.save(wstu);
			System.out.println(it.intValue()); // 1

			tx.commit();
			session.close();
		} catch (Exception e) {
			e.printStackTrace();
			if (tx != null)
				tx.rollback();
		}
	}

}
